---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      # - id: no-commit-to-branch
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        args:
          - --verbose
          - --redact

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args:
          - -i=2
          - -ci
          - -sr

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - --strict
          - -d
          - "{extends: relaxed, rules: {line-length: {max: 250}}}"

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.5.0
    hooks:
      - id: golangci-lint
        args:
          - --timeout=5m

  - repo: https://github.com/stackrox/kube-linter
    rev: v0.7.6
    hooks:
      - id: kube-linter

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_checkov
      - id: terraform_trivy
      # - id: terraform_docs
      #   args:
      #     - --hook-config=--create-file-if-not-exist=true
      #     - --hook-config=--add-to-existing-file=true
      #     - --args=--lockfile=false
      # - id: tfupdate
      #   name: Autoupdate AWS provider versions
      #   args:
      #    - --args=provider aws
  - repo: local
    hooks:
      - id: trivy
        name: trivy
        entry: trivy
        language: system
        args:
          - fs
          - .
          - --scanners
          - vuln,misconfig,secret
          - --severity
          - HIGH,CRITICAL
          - --exit-code
          - "1"
          - --skip-db-update
        pass_filenames: false
        always_run: true
      - id: rustfmt
        name: rustfmt
        entry: cargo
        language: system
        args:
          - fmt
          - --all
        files: \.rs$
        pass_filenames: false
      - id: clippy
        name: clippy
        entry: cargo
        language: system
        args:
          - clippy
          - --
          - -D
          - warnings
        files: \.rs$
        pass_filenames: false
      # - id: kubeconform
      #   name: kubeconform
      #   entry: bash -c "find . -name '*.yaml' -o -name '*.yml' | while read file; do if grep -q 'apiVersion:' \"\$file\" && grep -q 'kind:' \"\$file\" && grep -q 'metadata:' \"\$file\"; then echo \"\$file\"; fi; done | xargs -r kubeconform -debug"
      #   language: system
      #   files: \.(yaml|yml)$
      - id: helm-lint
        name: helm-lint
        entry: helm
        language: system
        types:
          - yaml
        files: ^Chart\.yaml$
        args:
          - lint
          - .
          - --quiet
      - id: gosec
        name: gosec
        entry: gosec
        language: system
        args:
          - ./...
          - -exclude-generated
          - -quiet
        types:
          - go
        pass_filenames: false
