services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs,dynamodb,lambda,apigateway,iam,cloudformation,cloudwatch,events,logs,stepfunctions,secretsmanager,kms,ssm,route53,ec2
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_data:/var/lib/localstack/data"
      - "./localstack_init:/docker-entrypoint-initaws.d"
